#!/bin/bash
preprocess () {
	IPTABLES=$(which iptables)
	if [ ! -z $IPTABLES ]; then
		IPTABLES_SAVE=$(which iptables-save)
		$IPTABLES_SAVE > /tmp/iptables_$(date +%F)
	else
		echo "iptables not found"
	fi

}
remove_inactive_rules () {
	IPTABLES_CHAINS="INPUT"
	for chain in $IPTABLES_CHAINS; do
		while (iptables -nvL $chain | grep -m 1 "0 ACCEPT"); do
			echo " $chain $rules_no";
			rules_no=$(iptables -nvL $chain --line | grep -m 1 "0 ACCEPT" | cut -d" " -f1)
			iptables -D $chain $rules_no; read;
			
			
		done;
	done;
	# for output chain remove all rules with state traacking and default drop
	iptables -I OUTPUT 1 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
	while [ ! -z "$(iptables -nvL OUTPUT 2)" ]; do
		iptables -D OUTPUT 2
	done;
}


remove_inactive_rules
